dev_test: &dev_test
  adapter: postgresql
  host: pg.hot-elm.test
  user: postgres
  password: postgres

development:
  <<: *dev_test
  database: dev

test:
  <<: *dev_test
  database: test

production:
  url: <%= ENV['DATABASE_URL'] %>